=== skolverket/dnp-provisioning-reference-api/src/main/resources/schema/group.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "/schemas/group",
  "title": "group",
  "description": "A group.",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "format": "uuid"
    },
    "displayName": {
      "type": "string"
    },
    "groupType": {
      "enum": [
        "Klass",
        "Schema",
        "Avdelning",
        "Ã–vrigt",
        "Undervisning",
        "Mentor",
        "Personalgrupp",
        "Provgrupp"
      ]
    },
    "schoolType": {
      "enum": [
        "FS",
        "FKLASS",
        "FTH",
        "OPPFTH",
        "GR",
        "GRS",
        "TR",
        "SP",
        "SAM",
        "GY",
        "GYS",
        "VUX",
        "VUXSFI",
        "VUXGR",
        "VUXGY",
        "VUXSARGR",
        "VUXSARTR",
        "VUXSARGY",
        "SFI",
        "SARVUX",
        "SARVUXGR",
        "SARVUXGY",
        "KU",
        "YH",
        "FHS",
        "STF",
        "KKU",
        "HS",
        "ABU",
        "AU"
      ]
    },
    "organisation": {
      "$ref": "/schemas/objectReference"
    },
    "groupMemberships": {
      "type": "array",
      "items": {
        "$ref": "/schemas/groupMembership"
      }
    }
  },
  "required": [
    "id",
    "displayName",
    "groupType",
    "organisation",
    "schoolType"
  ]
}

=== skolverket/dnp-provisioning-reference-api/src/test/resources/sampledata/group_json.json
{
  "id": "7b139724-9199-45f9-8591-6973a80d675a",
  "displayName": "llL7TwiELgfsyfu",
  "groupType": "Undervisning",
  "schoolType": "GR",
  "organisation": {
    "id": "b60a032a-afbc-595c-b167-b8b767be0e23",
    "displayName": "Mumin grundskola"
  },
  "groupMemberships": [
    {
      "id": "8907e5ad-e1be-4ac3-8769-ad57784e5f71",
      "person": {
        "id": "3b0840e9-fb9c-4618-9732-9f6f1627d038",
        "displayName": "Sister Kayli Reichel"
      }
    }
  ]
}
