=== skolverket/dnp-provisioning-reference-api/src/main/resources/schema/person.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "/schemas/person",
  "title": "Person",
  "description": "A person.",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "format": "uuid"
    },
    "givenName": {
      "type": "string"
    },
    "middleName": {
      "type": ["string", "null"]
    },
    "familyName": {
      "type": "string"
    },
    "eduPersonPrincipalNames": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1
    },
    "civicNo": {
      "$ref": "/schemas/personCivicNo"
    },
    "emails": {
      "type": "array",
      "items": {
        "$ref": "/schemas/email"
      }
    },
    "enrolments": {
      "type": "array",
      "items": {
        "$ref": "/schemas/enrolment"
      }
    }
  },
  "required": [
    "id",
    "givenName",
    "familyName",
    "eduPersonPrincipalNames",
    "civicNo"
  ]
}

=== skolverket/dnp-provisioning-reference-api/src/test/resources/sampledata/person.json
{
  "id": "123456789",
  "givenName": "Given Name Test",
  "middleName": "Middle Name Test",
  "familyName": "Family Name Test",
  "eduPersonPrincipalNames": [
    "elev1@soderhavetsgymnasium.se"
  ],
  "civicNo": {
    "value": "200112240129",
    "nationality": "SE"
  },
  "emails": [
    {
      "value": "elev1@soderhavetsgymnasium.se",
      "type": "Skola elev"
    }
  ],
  "enrolments": [
    {
      "enroledAt": {
        "id": "fa592db1-912b-57fe-8cf6-df5f81522f01",
        "displayName" : "enroledAt test value 1"
      },
      "schoolYear": 1,
      "schoolType": "GY",
      "cancelled": false,
      "educationCode": "TEST_ED_1",
      "programme": {
        "id": "fa592db1-912b-57fe-8cf9-df5f81422f02",
        "displayName" : "programme displayName test value 1"
      },
      "specification": "Additional information regarding the education"
    }
  ]
}
